spring.application.name=chatserver

# server
server.port=8080

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/chat_service?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qhdks00!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# h2 for test
# spring.datasource.h2.url=jdbc:h2:mem:testdb


# JWT Setting
jwt.issuer = Pray
jwt.secret-key = ZPrwmKmm6riceWAkRpLUwu3aROlKNa0x


######################## dev only ########################

# Spring Session JDBC Store
#spring.session.store-type=jdbc
#spring.session.jdbc.initialize-schema=always


##########################################################