/*
 * This source file was generated by the Gradle 'init' task
 */
package echoclient;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        EchoClient classUnderTest = new EchoClient();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
